import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const layoutPath = path.join(root, "hardware/layout/oso75.layout.json");
const layout = JSON.parse(fs.readFileSync(layoutPath, "utf8"));

const unit = layout.unit_mm;
const keys = layout.keys.map((key, index) => ({
  w: 1,
  h: 1,
  ...key,
  index,
  ref: `SW${index + 1}`,
  diode: `D${index + 1}`,
  cx: (key.x + (key.w ?? 1) / 2) * unit,
  cy: (key.y + (key.h ?? 1) / 2) * unit,
  pcbX: ((key.x + (key.w ?? 1) / 2) * unit) + 9,
  pcbY: ((key.y + (key.h ?? 1) / 2) * unit) + 9
}));

function ensureDir(filePath) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
}

function write(filePath, content) {
  ensureDir(filePath);
  fs.writeFileSync(filePath, content);
}

function keycodeFor(label) {
  const map = {
    Esc: "KC_ESC",
    "`": "KC_GRV",
    "-": "KC_MINS",
    "=": "KC_EQL",
    Backspace: "KC_BSPC",
    Tab: "KC_TAB",
    "[": "KC_LBRC",
    "]": "KC_RBRC",
    "\\": "KC_BSLS",
    Caps: "KC_CAPS",
    ";": "KC_SCLN",
    "'": "KC_QUOT",
    Enter: "KC_ENT",
    LShift: "KC_LSFT",
    RShift: "KC_RSFT",
    ",": "KC_COMM",
    ".": "KC_DOT",
    "/": "KC_SLSH",
    LCtrl: "KC_LCTL",
    LGUI: "KC_LGUI",
    LAlt: "KC_LALT",
    Space: "KC_SPC",
    RAlt: "KC_RALT",
    Fn: "MO(1)",
    Menu: "KC_APP",
    RCtrl: "KC_RCTL",
    PrtSc: "KC_PSCR",
    Ins: "KC_INS",
    Home: "KC_HOME",
    PgUp: "KC_PGUP",
    Del: "KC_DEL",
    End: "KC_END",
    PgDn: "KC_PGDN",
    Up: "KC_UP",
    Left: "KC_LEFT",
    Down: "KC_DOWN",
    Right: "KC_RGHT"
  };
  if (map[label]) return map[label];
  if (/^F\d+$/.test(label)) return `KC_${label}`;
  if (/^[A-Z]$/.test(label)) return `KC_${label}`;
  if (/^\d$/.test(label)) return `KC_${label}`;
  throw new Error(`No QMK keycode mapping for ${label}`);
}

function scadString() {
  const width = (Math.max(...keys.map(k => k.x + k.w)) * unit) + 18;
  const height = (Math.max(...keys.map(k => k.y + k.h)) * unit) + 18;
  const keyRows = keys
    .map(k => `  [${k.cx.toFixed(3)}, ${k.cy.toFixed(3)}, ${(k.w * unit).toFixed(3)}, ${(k.h * unit).toFixed(3)}, ${JSON.stringify(k.label)}]`)
    .join(",\n");
  return `// Generated by scripts/generate.mjs. Edit hardware/layout/oso75.layout.json.
$fn = 32;
unit = ${unit};
plate_thickness = 1.6;
case_wall = 4;
case_floor = 3;
switch_cutout = ${layout.switch_cutout_mm};
cluster_pad = 3.6;
plate_z = 14.5;
board_width = ${width.toFixed(3)};
board_height = ${height.toFixed(3)};
keys = [
${keyRows}
];

module rounded_rect_2d(size, radius) {
  offset(r = radius)
    square([max(0.1, size[0] - radius * 2), max(0.1, size[1] - radius * 2)], center = true);
}

module rounded_box(size, radius) {
  linear_extrude(height = size[2])
    translate([size[0] / 2, size[1] / 2])
      rounded_rect_2d([size[0], size[1]], radius);
}

module key_blob_2d(k, pad = cluster_pad) {
  translate([k[0] + 9, k[1] + 9])
    rounded_rect_2d([k[2] + pad * 2, k[3] + pad * 2], 4);
}

module keyboard_outline_2d(pad = cluster_pad) {
  union() {
    for (k = keys) key_blob_2d(k, pad);
  }
}

module switch_cutouts(depth = plate_thickness + 0.3) {
  for (k = keys) {
    translate([k[0] + 9, k[1] + 9, -0.15])
      cube([switch_cutout, switch_cutout, depth], center = true);
  }
}

module switch_wells() {
  for (k = keys) {
    translate([k[0] + 9, k[1] + 9, plate_thickness - 0.55])
      linear_extrude(height = 0.75)
        difference() {
          rounded_rect_2d([min(k[2] - 2.2, 17.4), 17.4], 1.5);
          square([switch_cutout, switch_cutout], center = true);
        }
  }
}

module stabilizer_slots() {
  for (k = keys) {
    if (k[2] >= unit * 1.75) {
      stab_spacing = k[2] >= unit * 5 ? 50 : 23.8;
      for (xoff = [-stab_spacing / 2, stab_spacing / 2]) {
        translate([k[0] + 9 + xoff, k[1] + 9, -0.2])
          cube([6.6, 12.4, plate_thickness + 0.5], center = true);
      }
    }
  }
}

module top_plate() {
  difference() {
    linear_extrude(height = plate_thickness)
      keyboard_outline_2d();
    switch_cutouts();
    stabilizer_slots();
  }
  switch_wells();
}

module tray_case() {
  difference() {
    linear_extrude(height = 14)
      keyboard_outline_2d(case_wall + cluster_pad);
    translate([0, 0, case_floor])
      linear_extrude(height = 15)
        keyboard_outline_2d(cluster_pad + 0.6);
    translate([board_width / 2 - 8, -3, 6])
      cube([16, 12, 5], center = false);
  }
}

module keycap_shadows() {
  for (k = keys) {
    translate([k[0] + 9, k[1] + 9, plate_z + plate_thickness + 0.45])
      linear_extrude(height = 1.2, scale = [0.94, 0.90])
        difference() {
          rounded_rect_2d([max(10, k[2] - 3.8), max(10, k[3] - 4.2)], 2.2);
          rounded_rect_2d([switch_cutout + 1.7, switch_cutout + 1.7], 1.4);
        }
  }
}

translate([0, 0, plate_z]) top_plate();
tray_case();
keycap_shadows();
`;
}

function keyboardJson() {
  const matrixPins = {
    rows: ["GP0", "GP1", "GP2", "GP3", "GP4", "GP5"],
    cols: ["GP6", "GP7", "GP8", "GP9", "GP10", "GP11", "GP12", "GP13", "GP14", "GP15", "GP16", "GP17", "GP18", "GP19", "GP20", "GP21"]
  };
  return JSON.stringify({
    manufacturer: "OSO",
    keyboard_name: "OSO75",
    maintainer: "OSO Keyboard contributors",
    bootloader: "rp2040",
    processor: "RP2040",
    diode_direction: "COL2ROW",
    features: {
      bootmagic: true,
      command: false,
      console: false,
      extrakey: true,
      mousekey: true,
      nkro: true
    },
    matrix_pins: matrixPins,
    usb: {
      device_version: "0.1.0",
      pid: "0x7501",
      vid: "0x4F53"
    },
    layouts: {
      LAYOUT: {
        layout: keys.map(k => ({
          label: k.label,
          matrix: [k.row, k.col],
          x: k.x,
          y: k.y,
          ...(k.w !== 1 ? { w: k.w } : {}),
          ...(k.h !== 1 ? { h: k.h } : {})
        }))
      }
    }
  }, null, 2) + "\n";
}

function keymapC() {
  const layer0 = keys.map(k => keycodeFor(k.label));
  const layer1 = keys.map(k => {
    const fn = {
      Esc: "QK_BOOT",
      "1": "KC_F1",
      "2": "KC_F2",
      "3": "KC_F3",
      "4": "KC_F4",
      "5": "KC_F5",
      "6": "KC_F6",
      "7": "KC_F7",
      "8": "KC_F8",
      "9": "KC_F9",
      "0": "KC_F10",
      "-": "KC_F11",
      "=": "KC_F12",
      Up: "KC_VOLU",
      Down: "KC_VOLD",
      Left: "KC_MPRV",
      Right: "KC_MNXT",
      Space: "KC_MPLY",
      Backspace: "KC_DEL"
    };
    return fn[k.label] ?? "KC_TRNS";
  });
  const rows = arr => arr.map((code, i) => `    ${code}${i === arr.length - 1 ? "" : ","}`).join("\n");
  return `// Generated by scripts/generate.mjs. Edit hardware/layout/oso75.layout.json.\n#include QMK_KEYBOARD_H\n\nconst uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {\n  [0] = LAYOUT(\n${rows(layer0)}\n  ),\n  [1] = LAYOUT(\n${rows(layer1)}\n  )\n};\n`;
}

function placementCsv() {
  const header = "ref,type,label,row,col,x_mm,y_mm,rotation,footprint\n";
  const rows = keys.flatMap(k => [
    `${k.ref},switch,${JSON.stringify(k.label)},${k.row},${k.col},${k.pcbX.toFixed(3)},${k.pcbY.toFixed(3)},0,MX_Hotswap_1u`,
    `${k.diode},diode,${JSON.stringify(k.label)},${k.row},${k.col},${(k.pcbX + 6.5).toFixed(3)},${(k.pcbY + 6.5).toFixed(3)},90,D_SOD-123`
  ]);
  return header + rows.join("\n") + "\n";
}

function csv(value) {
  const text = String(value ?? "");
  return /[",\n]/.test(text) ? JSON.stringify(text) : text;
}

function matrixNetlistCsv() {
  const header = [
    "switch_ref",
    "diode_ref",
    "label",
    "row",
    "col",
    "switch_pin_1",
    "switch_pin_2",
    "diode_anode",
    "diode_cathode",
    "column_net",
    "row_net",
    "x_mm",
    "y_mm"
  ].join(",");
  const rows = keys.map(k => [
    k.ref,
    k.diode,
    k.label,
    k.row,
    k.col,
    `COL${k.col}`,
    `${k.diode}_A`,
    `${k.diode}_A`,
    `ROW${k.row}`,
    `COL${k.col}`,
    `ROW${k.row}`,
    k.pcbX.toFixed(3),
    k.pcbY.toFixed(3)
  ].map(csv).join(","));
  return `${header}\n${rows.join("\n")}\n`;
}

function componentCsv() {
  const fixed = [
    ["U1", "RP2040", "QFN-56", "RP2040", "factory", "Main MCU"],
    ["U2", "W25Q128JVSIQ or compatible", "SOIC-8 208mil", "W25Q128JVSIQ", "factory", "16 MB QSPI flash"],
    ["U3", "3.3 V LDO", "SOT-23-5", "AP2112K-3.3TRG1", "factory", "USB 5 V to 3.3 V"],
    ["U4", "USB ESD array", "SOT-23-6", "USBLC6-2SC6 or equivalent", "factory", "Place by USB-C"],
    ["J1", "USB-C receptacle", "USB-C-16P-SMD", "HRO TYPE-C-31-M-12", "factory", "USB 2.0 device port"],
    ["J2", "SWD header", "1x04 1.27mm or tag-connect", "DNP header option", "optional", "3V3 SWDIO SWCLK GND"],
    ["Y1", "12 MHz crystal", "3225 crystal", "12 MHz CL matched", "factory", "RP2040 clock"],
    ["SW_BOOT", "Boot tactile switch", "SMD tactile", "SKRPACE010", "factory", "Pull QSPI_SS low while reset"],
    ["SW_RESET", "Reset tactile switch", "SMD tactile", "SKRPACE010", "factory", "Pull RUN low"],
    ["D85", "Status LED", "0603 LED", "Green 0603", "factory", "Driven by GP22 through R9"],
    ["R1", "5.1k", "0603", "generic", "factory", "USB-C CC1 pulldown"],
    ["R2", "5.1k", "0603", "generic", "factory", "USB-C CC2 pulldown"],
    ["R3", "27R", "0603", "generic", "factory", "USB D+ series"],
    ["R4", "27R", "0603", "generic", "factory", "USB D- series"],
    ["R5", "100k", "0603", "generic", "factory", "RUN pullup"],
    ["R6", "100k", "0603", "generic", "factory", "QSPI_SS pullup"],
    ["R7", "100k", "0603", "generic", "factory", "VBUS sense high divider"],
    ["R8", "100k", "0603", "generic", "factory", "VBUS sense low divider"],
    ["R9", "1k", "0603", "generic", "factory", "Status LED current limit"],
    ["C1", "10uF", "0603/0805", "generic X5R", "factory", "LDO input"],
    ["C2", "10uF", "0603/0805", "generic X5R", "factory", "LDO output"],
    ["C3", "1uF", "0603", "generic X5R", "factory", "RP2040 VREG_OUT"],
    ["C4", "1uF", "0603", "generic X5R", "factory", "RP2040 ADC_AVDD filter"],
    ["C5", "18pF", "0603", "match crystal CL", "factory", "Crystal load"],
    ["C6", "18pF", "0603", "match crystal CL", "factory", "Crystal load"]
  ];
  const decoupling = Array.from({ length: 14 }, (_, i) => [
    `C${7 + i}`,
    "100nF",
    "0603",
    "generic X7R",
    "factory",
    "RP2040/flash local decoupling"
  ]);
  const matrix = keys.flatMap(k => [
    [k.ref, "MX hotswap socket", "Kailh MX hotswap", "CPG151101S11", "builder or factory", `${k.label} switch`],
    [k.diode, "1N4148W", "SOD-123", "1N4148W", "factory", `${k.label} anti-ghosting diode`]
  ]);
  const header = "ref,value,footprint,mpn,assembly,notes";
  return `${header}\n${[...fixed, ...decoupling, ...matrix].map(row => row.map(csv).join(",")).join("\n")}\n`;
}

function rp2040NetlistCsv() {
  const rows = [
    ["J1", "A1/B1/A12/B12", "GND", "USB-C shell and ground pins"],
    ["J1", "A4/B4/A9/B9", "VBUS", "USB 5 V input"],
    ["J1", "CC1", "USB_CC1", "To R1 5.1k pulldown"],
    ["J1", "CC2", "USB_CC2", "To R2 5.1k pulldown"],
    ["J1", "A6/B6", "USB_DP_CONN", "To U4 ESD then R3"],
    ["J1", "A7/B7", "USB_DM_CONN", "To U4 ESD then R4"],
    ["R1", "1", "USB_CC1", "USB-C device advertise"],
    ["R1", "2", "GND", "5.1k pulldown"],
    ["R2", "1", "USB_CC2", "USB-C device advertise"],
    ["R2", "2", "GND", "5.1k pulldown"],
    ["U4", "IO1", "USB_DP_CONN", "Connector side D+"],
    ["U4", "IO2", "USB_DM_CONN", "Connector side D-"],
    ["U4", "GND", "GND", "Short path to connector ground"],
    ["R3", "1", "USB_DP_CONN", "USB series resistor"],
    ["R3", "2", "USB_DP", "RP2040 side D+"],
    ["R4", "1", "USB_DM_CONN", "USB series resistor"],
    ["R4", "2", "USB_DM", "RP2040 side D-"],
    ["U3", "IN", "VBUS", "5 V from USB"],
    ["U3", "OUT", "+3V3", "Main 3.3 V rail"],
    ["U3", "GND", "GND", "Power ground"],
    ["C1", "1", "VBUS", "LDO input cap"],
    ["C1", "2", "GND", "LDO input cap"],
    ["C2", "1", "+3V3", "LDO output cap"],
    ["C2", "2", "GND", "LDO output cap"],
    ["U1", "USB_DP", "USB_DP", "Native USB D+"],
    ["U1", "USB_DM", "USB_DM", "Native USB D-"],
    ["U1", "VREG_IN", "+3V3", "RP2040 internal regulator input"],
    ["U1", "VREG_OUT", "+1V1", "RP2040 internal regulator output"],
    ["U1", "IOVDD/ADC_AVDD/USB_VDD", "+3V3", "3.3 V I/O, ADC, and USB PHY supplies, locally decoupled"],
    ["U1", "DVDD", "+1V1", "Digital core supply from VREG_OUT, locally decoupled"],
    ["U1", "GND", "GND", "All ground pins and exposed pad"],
    ["U1", "RUN", "RESET_N", "Pull up to 3V3, SW_RESET pulls low"],
    ["SW_RESET", "1", "RESET_N", "Reset button"],
    ["SW_RESET", "2", "GND", "Reset button"],
    ["U1", "QSPI_SS", "FLASH_CS_N", "Flash chip-select and boot button"],
    ["SW_BOOT", "1", "FLASH_CS_N", "Bootsel button"],
    ["SW_BOOT", "2", "GND", "Hold low while resetting for UF2"],
    ["U1", "XIN", "XTAL_IN", "12 MHz crystal"],
    ["U1", "XOUT", "XTAL_OUT", "12 MHz crystal"],
    ["Y1", "1", "XTAL_IN", "Crystal pin"],
    ["Y1", "2", "XTAL_OUT", "Crystal pin"],
    ["C5", "1", "XTAL_IN", "Crystal load cap"],
    ["C5", "2", "GND", "Crystal load cap"],
    ["C6", "1", "XTAL_OUT", "Crystal load cap"],
    ["C6", "2", "GND", "Crystal load cap"],
    ["U2", "CS", "FLASH_CS_N", "QSPI flash"],
    ["U2", "CLK", "QSPI_SCLK", "QSPI flash"],
    ["U2", "IO0", "QSPI_SD0", "QSPI flash"],
    ["U2", "IO1", "QSPI_SD1", "QSPI flash"],
    ["U2", "IO2", "QSPI_SD2", "QSPI flash"],
    ["U2", "IO3", "QSPI_SD3", "QSPI flash"],
    ["U2", "VCC", "+3V3", "QSPI flash power"],
    ["U2", "GND", "GND", "QSPI flash ground"],
    ["U1", "QSPI_SCLK", "QSPI_SCLK", "QSPI flash clock"],
    ["U1", "QSPI_SD0", "QSPI_SD0", "QSPI flash data"],
    ["U1", "QSPI_SD1", "QSPI_SD1", "QSPI flash data"],
    ["U1", "QSPI_SD2", "QSPI_SD2", "QSPI flash data"],
    ["U1", "QSPI_SD3", "QSPI_SD3", "QSPI flash data"],
    ["R7", "1", "VBUS", "VBUS sense divider high"],
    ["R7", "2", "VBUS_SENSE", "VBUS sense divider high"],
    ["R8", "1", "VBUS_SENSE", "VBUS sense divider low"],
    ["R8", "2", "GND", "VBUS sense divider low"],
    ["U1", "GP24", "VBUS_SENSE", "Optional USB present sense"],
    ["U1", "GP22", "LED_STATUS", "Status LED drive"],
    ["R9", "1", "LED_STATUS", "LED current limit"],
    ["R9", "2", "D85_A", "Status LED anode"],
    ["D85", "A", "D85_A", "Status LED"],
    ["D85", "K", "GND", "Status LED"],
    ["J2", "1", "+3V3", "SWD header"],
    ["J2", "2", "SWDIO", "SWD header"],
    ["J2", "3", "SWCLK", "SWD header"],
    ["J2", "4", "GND", "SWD header"],
    ["U1", "SWDIO", "SWDIO", "Debug"],
    ["U1", "SWCLK", "SWCLK", "Debug"]
  ];

  const rowPins = ["GP0", "GP1", "GP2", "GP3", "GP4", "GP5"];
  const colPins = ["GP6", "GP7", "GP8", "GP9", "GP10", "GP11", "GP12", "GP13", "GP14", "GP15", "GP16", "GP17", "GP18", "GP19", "GP20", "GP21"];
  rowPins.forEach((pin, index) => rows.push(["U1", pin, `ROW${index}`, `Keyboard matrix row ${index}`]));
  colPins.forEach((pin, index) => rows.push(["U1", pin, `COL${index}`, `Keyboard matrix column ${index}`]));
  rows.push(["U1", "GP26", "ENC_A", "Optional encoder A"]);
  rows.push(["U1", "GP27", "ENC_B", "Optional encoder B"]);
  rows.push(["U1", "GP28", "I2C_SDA", "Optional OLED/header SDA"]);
  rows.push(["U1", "GP29", "I2C_SCL", "Optional OLED/header SCL"]);

  const header = "ref,pin,net,notes";
  return `${header}\n${rows.map(row => row.map(csv).join(",")).join("\n")}\n`;
}

function circuitMarkdown() {
  const rowPins = ["GP0", "GP1", "GP2", "GP3", "GP4", "GP5"];
  const colPins = ["GP6", "GP7", "GP8", "GP9", "GP10", "GP11", "GP12", "GP13", "GP14", "GP15", "GP16", "GP17", "GP18", "GP19", "GP20", "GP21"];
  const matrixRows = rowPins.map((pin, index) => `| ROW${index} | U1 ${pin} | ${keys.filter(k => k.row === index).length} switches |`).join("\n");
  const matrixCols = colPins.map((pin, index) => `| COL${index} | U1 ${pin} | ${keys.filter(k => k.col === index).length} switches |`).join("\n");
  return `# OSO75 Circuit Design\n\nThis is the first real circuit pass for the OSO75 custom PCB. It defines the MCU\nsupport circuit, USB-C input, matrix wiring, diode direction, and assembly intent.\nUse the generated CSV files next to this document as the source of truth for\nschematic capture.\n\n## Electrical Target\n\n- MCU: onboard RP2040, QFN-56.\n- Firmware: QMK/VIA-compatible matrix using native USB.\n- Matrix: 6 rows x 16 columns, 84 populated switch positions.\n- Diode direction: \`COL2ROW\`.\n- Builder soldering target: switches/stabilizers only. SMD diodes and controller\n  support parts should be factory assembled.\n\n## Switch Matrix\n\nEach key uses this net order:\n\n\`\`\`text\nCOLn -> switch -> diode anode -> diode cathode -> ROWm\n\`\`\`\n\nThat matches QMK \`COL2ROW\`: conventional current flows from the selected column\nthrough the switch and diode into the sensed row.\n\n### Rows\n\n| Net | RP2040 pin | Populated keys |\n|---|---|---:|\n${matrixRows}\n\n### Columns\n\n| Net | RP2040 pin | Populated keys |\n|---|---|---:|\n${matrixCols}\n\n## USB-C And Power\n\n- J1 is a USB-C receptacle wired as a USB 2.0 device.\n- CC1 and CC2 each get a 5.1k pulldown to GND.\n- D+ and D- route from J1 through U4 ESD protection, then through 27R series\n  resistors to RP2040 USB_DP/USB_DM.\n- VBUS feeds U3, a 3.3 V LDO such as AP2112K-3.3.\n- C1 and C2 are 10uF bulk capacitors at LDO input/output.\n- R7/R8 create a 100k/100k VBUS sense divider into GP24.\n\n## RP2040 Support\n\n- U2 is a 16 MB QSPI flash such as W25Q128JVSIQ.\n- Y1 is a 12 MHz crystal with load capacitors sized to the chosen crystal.\n- SW_RESET pulls RUN low.\n- SW_BOOT pulls FLASH_CS_N/QSPI_SS low for UF2 bootloader entry.\n- J2 exposes 3V3, SWDIO, SWCLK, and GND for rescue/debug.\n- GP22 drives a status LED through R9.\n- GP26/GP27 are reserved for an optional encoder.\n- GP28/GP29 are reserved for optional I2C expansion.\n\n## Layout Rules\n\n- Put J1, U4, R3, and R4 close together at the front USB port.\n- Keep D+/D- short, parallel, and away from the switch matrix where possible.\n- Put U1, U2, Y1, and their decoupling caps in one controller cluster.\n- Place one 100nF cap near each RP2040 supply pin group and one near U2.\n- Route rows horizontally and columns vertically where possible.\n- Put the SOD-123 diode near each hotswap socket; cathode stripe goes to the row net.\n- Use a solid ground fill on both layers, stitched around USB and MCU.\n\n## Generated Files\n\n- \`oso75_matrix_netlist.csv\`: one switch/diode row per key.\n- \`oso75_rp2040_netlist.csv\`: MCU, USB, power, flash, crystal, buttons, and headers.\n- \`oso75_components.csv\`: component list with footprints and assembly intent.\n- \`oso75_placement.csv\`: switch and diode coordinates from the keyboard layout.\n\n`;
}

function pinPlanMarkdown() {
  return `# OSO75 RP2040 Pin Plan\n\nThe first custom PCB target uses an onboard RP2040 and a 6 x 16 keyboard matrix.\nThis gives 96 matrix positions for the 84 physical keys, leaving spare positions for\nfuture encoder, macro, or alternate layout variants.\n\n## Matrix\n\n| Signal | Pins |\n|---|---|\n| Rows | GP0, GP1, GP2, GP3, GP4, GP5 |\n| Columns | GP6, GP7, GP8, GP9, GP10, GP11, GP12, GP13, GP14, GP15, GP16, GP17, GP18, GP19, GP20, GP21 |\n| Diode direction | COL2ROW |\n| Per-key wiring | COLn -> switch -> diode anode -> diode cathode -> ROWm |\n\n## Reserved Pins\n\n| Purpose | Pin |\n|---|---|\n| USB D+ / D- | RP2040 native USB_DP / USB_DM pins |\n| USB VBUS sense | GP24 through 100k/100k divider |\n| Status LED | GP22 |\n| Optional encoder A/B | GP26 / GP27 |\n| Optional OLED I2C | GP28 / GP29 |\n| Reset | RUN pulled high, reset switch pulls low |\n| Boot | QSPI_SS/FLASH_CS_N pulled high, boot switch pulls low |\n| Debug | SWDIO / SWCLK on optional header |\n\n## Assembly Intent\n\nJLCPCB/PCBWay should assemble the RP2040, crystal, flash, USB-C connector,\nESD protection, reset/boot buttons, SMD diodes, and passives. The builder should\nonly need to install switches, stabilizers, and case hardware.\n\nSee \`oso75_circuit.md\`, \`oso75_matrix_netlist.csv\`, and\n\`oso75_rp2040_netlist.csv\` for the actual circuit nets.\n`;
}

function bomMarkdown() {
  return `# OSO75 Initial BOM\n\nThis BOM is split between parts we want assembled on the PCB and parts the builder\ninstalls manually.\n\n## PCB Factory Assembly\n\n| Qty | Part | Notes |\n|---:|---|---|\n| 1 | RP2040 | Onboard MCU |\n| 1 | 16MB QSPI flash | Prefer W25Q128-compatible footprint |\n| 1 | 12 MHz crystal | RP2040 reference design |\n| 84 | 1N4148W SOD-123 diodes | One per switch, factory assembled |\n| 1 | USB-C receptacle | USB 2.0 device wiring |\n| 1 | USB ESD protection | Near USB-C port |\n| 2 | 5.1k CC resistors | USB-C device mode |\n| 1 | Reset tactile switch | SMD or through-hole |\n| 1 | Boot tactile switch | For UF2 flashing |\n| many | 0402/0603 passives | Per RP2040 reference schematic |\n\n## Builder Assembly\n\n| Qty | Part | Current pick |\n|---:|---|---|\n| 84-90 | MX switches | Gateron Milky Yellow Pro V3 or MMD Princess V4 |\n| 84 | Kailh MX hotswap sockets | Only if not factory assembled |\n| 1 set | PCB screw-in stabilizers | 6.25u + 2u set |\n| 1 | Plate | Generated from OpenSCAD or laser-cut DXF later |\n| 1 | Case | Generated from OpenSCAD tray model |\n| 1 | USB-C cable | Data-capable cable |\n\n`;
}

write(path.join(root, "hardware/cad/generated/oso75_case_plate.scad"), scadString());
write(path.join(root, "qmk/keyboards/oso/oso75/keyboard.json"), keyboardJson());
write(path.join(root, "qmk/keyboards/oso/oso75/keymaps/default/keymap.c"), keymapC());
write(path.join(root, "hardware/pcb/oso75_placement.csv"), placementCsv());
write(path.join(root, "hardware/pcb/oso75_matrix_netlist.csv"), matrixNetlistCsv());
write(path.join(root, "hardware/pcb/oso75_components.csv"), componentCsv());
write(path.join(root, "hardware/pcb/oso75_rp2040_netlist.csv"), rp2040NetlistCsv());
write(path.join(root, "hardware/pcb/oso75_circuit.md"), circuitMarkdown());
write(path.join(root, "hardware/pcb/rp2040-pin-plan.md"), pinPlanMarkdown());
write(path.join(root, "hardware/bom.md"), bomMarkdown());

console.log(`Generated ${keys.length} keys.`);
